image: maven:3.3-jdk-8

build:
   stage: build
   script:
     - 'mvn clean'

test:
   stage: confidence-check
   services:
     - selenium/standalone-chrome
   script:
     - npm run confidence-check --host=selenium__standalone-chrome
   stage: test
   script:
     - 'mvn test'
   artifacts:
     paths:
     - target/cucumber-results-feature-overview.html
     - Reports/STA-Automation.html
